function changsheng(a) {
	var jieguo = {
'甲': '',
'乙': '',
'丙': '',
'丁': '',
'戊': '',
'己': '',
'庚': '',
'辛': '',
'壬': '',
'癸': '',
'甲子': '沐<font color=#999>凶</font>',
'乙丑': '衰<font color=#999>弱</font>',
'丙寅': '生<font color=#999>强</font>',
'丁卯': '病<font color=#999>弱</font>',
'戊辰': '冠<font color=#999>吉</font>',
'己巳': '旺<font color=#999>吉<!--大吉--></font>',
'庚午': '沐<font color=#999>凶</font>',
'辛未': '衰<font color=#999>弱</font>',
'壬申': '生<font color=#999>强</font>',
'癸酉': '病<font color=#999>弱</font>',
'甲戌': '养<font color=#999>平</font>',
'乙亥': '死<font color=#999>凶</font>',
'丙子': '胎<font color=#999>平</font>',
'丁丑': '墓<font color=#999>吉</font>',
'戊寅': '生<font color=#999>强</font>',
'己卯': '病<font color=#999>弱</font>',
'庚辰': '养<font color=#999>平</font>',
'辛巳': '死<font color=#999>凶</font>',
'壬午': '胎<font color=#999>平</font>',
'癸未': '墓<font color=#999>吉</font>',
'甲申': '绝<font color=#999>凶</font>',
'乙酉': '绝<font color=#999>凶</font>',
'丙戌': '墓<font color=#999>吉</font>',
'丁亥': '胎<font color=#999>平</font>',
'戊子': '胎<font color=#999>平</font>',
'己丑': '墓<font color=#999>吉</font>',
'庚寅': '绝<font color=#999>凶</font>',
'辛卯': '绝<font color=#999>凶</font>',
'壬辰': '墓<font color=#999>吉</font>',
'癸巳': '胎<font color=#999>平</font>',
'甲午': '死<font color=#999>凶</font>',
'乙未': '养<font color=#999>平</font>',
'丙申': '病<font color=#999>弱</font>',
'丁酉': '生<font color=#999>强</font>',
'戊戌': '墓<font color=#999>吉</font>',
'己亥': '胎<font color=#999>平</font>',
'庚子': '死<font color=#999>凶</font>',
'辛丑': '养<font color=#999>平</font>',
'壬寅': '病<font color=#999>弱</font>',
'癸卯': '生<font color=#999>强</font>',
'甲辰': '衰<font color=#999>弱</font>',
'乙巳': '沐<font color=#999>凶</font>',
'丙午': '旺<font color=#999>吉<!--大吉--></font>',
'丁未': '冠<font color=#999>吉</font>',
'戊申': '病<font color=#999>弱</font>',
'己酉': '生<font color=#999>强</font>',
'庚戌': '衰<font color=#999>弱</font>',
'辛亥': '沐<font color=#999>凶</font>',
'壬子': '旺<font color=#999>吉<!--大吉--></font>',
'癸丑': '冠<font color=#999>吉</font>',
'甲寅': '临<font color=#999>吉<!--大吉--></font>',
'乙卯': '临<font color=#999>吉<!--大吉--></font>',
'丙辰': '冠<font color=#999>吉</font>',
'丁巳': '旺<font color=#999>吉<!--大吉--></font>',
'戊午': '旺<font color=#999>吉<!--大吉--></font>',
'己未': '冠<font color=#999>吉</font>',
'庚申': '临<font color=#999>吉<!--大吉--></font>',
'辛酉': '临<font color=#999>吉<!--大吉--></font>',
'壬戌': '冠<font color=#999>吉</font>',
'癸亥': '旺<font color=#999>吉<!--大吉--></font>',
'甲亥': '生<font color=#999>强</font>',
'乙子': '病<font color=#999>弱</font>',
'丙卯': '沐<font color=#999>凶</font>',
'丁子': '绝<font color=#999>凶</font>',
'戊卯': '沐<font color=#999>凶</font>',
'己子': '绝<font color=#999>凶</font>',
'庚丑': '墓<font color=#999>吉</font>',
'辛子': '生<font color=#999>强</font>',
'壬丑': '衰<font color=#999>弱</font>',
'癸子': '临<font color=#999>吉<!--大吉--></font>',
'甲丑': '冠<font color=#999>吉</font>',
'乙午': '生<font color=#999>强</font>',
'丙巳': '临<font color=#999>吉<!--大吉--></font>',
'丁寅': '死<font color=#999>凶</font>',
'戊巳': '临<font color=#999>吉<!--大吉--></font>',
'己寅': '死<font color=#999>凶</font>',
'庚卯': '胎<font color=#999>平</font>',
'辛寅': '胎<font color=#999>平</font>',
'壬卯': '死<font color=#999>凶</font>',
'癸寅': '沐<font color=#999>凶</font>',
'甲卯': '旺<font color=#999>吉<!--大吉--></font>',
'乙辰': '冠<font color=#999>吉</font>',
'丙未': '衰<font color=#999>弱</font>',
'丁辰': '衰<font color=#999>弱</font>',
'戊未': '衰<font color=#999>弱</font>',
'己辰': '衰<font color=#999>弱</font>',
'庚巳': '生<font color=#999>强</font>',
'辛辰': '墓<font color=#999>吉</font>',
'壬巳': '绝<font color=#999>凶</font>',
'癸辰': '养<font color=#999>平</font>',
'甲巳': '病<font color=#999>弱</font>',
'乙寅': '旺<font color=#999>吉<!--大吉--></font>',
'丙酉': '死<font color=#999>凶</font>',
'丁午': '临<font color=#999>吉<!--大吉--></font>',
'戊酉': '死<font color=#999>凶</font>',
'己午': '临<font color=#999>吉<!--大吉--></font>',
'庚未': '冠<font color=#999>吉</font>',
'辛午': '病<font color=#999>弱</font>',
'壬未': '养<font color=#999>平</font>',
'癸午': '绝<font color=#999>凶</font>',
'甲未': '墓<font color=#999>吉</font>',
'乙戌': '墓<font color=#999>吉</font>',
'丙亥': '绝<font color=#999>凶</font>',
'丁申': '沐<font color=#999>凶</font>',
'戊亥': '绝<font color=#999>凶</font>',
'己申': '生<font color=#999>强</font>',
'庚酉': '旺<font color=#999>吉<!--大吉--></font>',
'辛申': '旺<font color=#999>吉<!--大吉--></font>',
'壬酉': '沐<font color=#999>凶</font>',
'癸申': '死<font color=#999>凶</font>',
'甲酉': '胎<font color=#999>平</font>',
'乙申': '胎<font color=#999>平</font>',
'丙丑': '养<font color=#999>平</font>',
'丁戌': '养<font color=#999>平</font>',
'戊丑': '养<font color=#999>平</font>',
'己戌': '养<font color=#999>平</font>',
'庚亥': '病<font color=#999>弱</font>',
'辛戌': '冠<font color=#999>吉</font>',
'壬亥': '临<font color=#999>吉<!--大吉--></font>',
'癸戌': '衰<font color=#999>弱'
	};
	var abcd = jieguo[a];
	return abcd;
}