function ccdd(){document.getElementById('result').style.display='none';document.getElementById('yun').style.display='none';document.getElementById('liu-yue').style.display='none';document.getElementById('liupai').style.display='none';document.getElementById('tishi').style.display='none';document.getElementById('yincang').style.display='';document.getElementById('xianshi').style.display='none';document.getElementById('xxyyss').style.display='none';}
function ddee(){document.getElementById('hlyincang').style.display='';document.getElementById('huangli').style.display='none';document.getElementById('hlxianshi').style.display='none';}
function abcd(){document.getElementById('result').style.display='';document.getElementById('yun').style.display='';document.getElementById('liu-yue').style.display='';document.getElementById('liupai').style.display='';document.getElementById('tishi').style.display='';document.getElementById('yincang').style.display='none';document.getElementById('xianshi').style.display='';document.getElementById('xxyyss').style.display='';}
function dcba(){document.getElementById('hlyincang').style.display='none';document.getElementById('huangli').style.display='';document.getElementById('hlxianshi').style.display='';}
function xsys()
{document.getElementById('xsys').style.backgroundColor='#EEEEEE';document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji1.js"
var request=new XMLHttpRequest();request.open("get",url);request.send(null);request.onload=function(){var rigan=bazi.getDay().substr(0,1);var yuezhi=bazi.getMonth().substr(-1);var riganyuezhi=rigan+yuezhi;var txt2='';txt2+='喜用神：'+xiyongshen(riganyuezhi);if(request.status==200){var json=JSON.parse(request.responseText);var yuezhi1=bazi.getMonth().substr(-1);var rigan1=bazi.getDay().substr(0,1);var yzrg1='';yzrg1+=yuezhi1+','+rigan1;var ttt='';$('#span666').html('月支/日干：'+yzrg1);for(var i=0;i<json.data.length;i++){if(json.data[i].key==yzrg1){ttt+=json.data[i].content+'<br>';}}}
$('#text666').html('<b style="color:#000000;">月支/日干：'+yzrg1+'</b><br>'+txt2+'<br><br>'+ttt);}}
function dtss()
{document.getElementById('dtss').style.backgroundColor='#EEEEEE';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji2.js"
var request=new XMLHttpRequest();request.open("get",url);request.send(null);request.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var yuezhi1=bazi.getMonth().substr(-1);var rigan1=bazi.getDay().substr(0,1);var yzrg1='';yzrg1+=yuezhi1+','+rigan1;var ttt='';$('#span666').html('日干：'+rigan1);for(var i=0;i<json.data.length;i++){if(json.data[i].key==rigan1){ttt+=json.data[i].content+'<br>';$('#text666').html('<b style="color:#000000;">日干：'+rigan1+'</b><br>'+ttt);}}}}}
function smth()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#EEEEEE';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji3_1.js"
var url2="guji3_2.js"
var url3="guji3_3.js"
var url4="guji3_4.js"
var request=new XMLHttpRequest();var request2=new XMLHttpRequest();var request3=new XMLHttpRequest();var request4=new XMLHttpRequest();request.open("get",url);request2.open("get",url2);request3.open("get",url3);request4.open("get",url4);request.send(null);request2.send(null);request3.send(null);request4.send(null);request.onload=request2.onload=request3.onload=request4.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var heji='';heji+=bazi.getDay()+','+bazi.getTime();var ttt='';$('#span666').html('日柱/时柱：'+heji);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ttt+=json.data[i].content+'<br>';}}}
if(request2.status==200){var json2=JSON.parse(request2.responseText);var heji2='';heji2+=bazi.getDay().substr(0,1);var ttt2='';$('#span777').html('日干：'+heji2);for(var i=0;i<json2.data.length;i++){if(json2.data[i].key==heji2){ttt2+=json2.data[i].content+'<br>';}}}
if(request3.status==200){var json3=JSON.parse(request3.responseText);var heji3='';heji3+=bazi.getMonth().substr(-1)+','+bazi.getDay().substr(0,1);var ttt3='';$('#span888').html('月支/日干：'+heji3);for(var i=0;i<json3.data.length;i++){if(json3.data[i].key==heji3){ttt3+=json3.data[i].content+'<br>';}}}
if(request4.status==200){var json4=JSON.parse(request4.responseText);var rigan1=bazi.getDay().substr(0,1);var wuxing='';if(rigan1=='甲'||rigan1=='乙'){wuxing='木';}
if(rigan1=='丙'||rigan1=='丁'){wuxing='火';}
if(rigan1=='戊'||rigan1=='己'){wuxing='土';}
if(rigan1=='庚'||rigan1=='辛'){wuxing='金';}
if(rigan1=='壬'||rigan1=='癸'){wuxing='水';}
var heji4='';heji4+=bazi.getMonth().substr(-1)+','+wuxing;var ttt4='';$('#span999').html('月支/日干五行：'+heji4);for(var i=0;i<json4.data.length;i++){if(json4.data[i].key==heji4){ttt4+=json4.data[i].content+'<br>';}}}
$('#text666').html('<b style="color:#000000;">日柱/时柱：'+heji+'：</b><br>'+ttt+'<b style="color:#000000;">日干：'+heji2+'：</b><br>'+ttt2+'<b style="color:#000000;">月支/日干：'+heji3+'：</b><br>'+ttt3+'<b style="color:#000000;">月支/日干五行：'+heji4+'：</b><br>'+ttt4);}}
function sftk()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#EEEEEE';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji4_1.js"
var url2="guji4_2.js"
var url3="guji4_3.js"
var request=new XMLHttpRequest();var request2=new XMLHttpRequest();var request3=new XMLHttpRequest();request.open("get",url);request2.open("get",url2);request3.open("get",url3);request.send(null);request2.send(null);request3.send(null);request.onload=request2.onload=request3.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var heji='';heji+=bazi.getDay().substr(0,1)+','+bazi.getMonth().substr(-1);var ttt='';$('#span666').html('日干/月支：'+heji);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ttt+=json.data[i].content+'<br>';}}}
if(request2.status==200){var json2=JSON.parse(request2.responseText);var heji2='';heji2+=bazi.getDay().substr(0,1);var ttt2='';$('#span777').html('日干：'+heji2);for(var i=0;i<json2.data.length;i++){if(json2.data[i].key==heji2){ttt2+=json2.data[i].content+'<br>';}}}
if(request3.status==200){var json3=JSON.parse(request3.responseText);var heji3='';heji3+=bazi.getMonth().substr(-1);var ttt3='';$('#span888').html('月支：'+heji3);for(var i=0;i<json3.data.length;i++){if(json3.data[i].key==heji3){ttt3+=json3.data[i].content+'<br>';}}}
$('#text666').html('<b style="color:#000000;">日干/月支：'+heji+'：</b><br>'+ttt+'<b style="color:#000000;">日干：'+heji2+'：</b><br>'+ttt2+'<b style="color:#000000;">月支：'+heji3+'：</b><br>'+ttt3);}}
function bzty()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#EEEEEE';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji5_1.js"
var url2="guji5_2.js"
var url3="guji5_3.js"
var request=new XMLHttpRequest();var request2=new XMLHttpRequest();var request3=new XMLHttpRequest();request.open("get",url);request2.open("get",url2);request3.open("get",url3);request.send(null);request2.send(null);request3.send(null);request.onload=request2.onload=request3.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var heji='';heji+=bazi.getDay();var ttt='';$('#span666').html('日柱：'+heji);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ttt+=json.data[i].content+'<br>';}}}
if(request2.status==200){var json=JSON.parse(request2.responseText);var heji2='';heji2+=bazi.getDay().substr(0,1)+','+bazi.getTime().substr(-1);var ttt2='';$('#span777').html('日干/时支：'+heji2);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji2){ttt2+=json.data[i].content+'<br>';}}}
if(request3.status==200){var json=JSON.parse(request3.responseText);var heji3='';heji3+=bazi.getDay().substr(0,1);var ttt3='';$('#span888').html('日干：'+heji3);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji3){ttt3+=json.data[i].content+'<br>';}}}
$('#text666').html('<b style="color:#000000;">日柱：'+heji+'</b><br>'+ttt+'<b style="color:#000000;">日干/时支：'+heji2+'</b><br>'+ttt2+'<b style="color:#000000;">日干：'+heji3+'</b><br>'+ttt3);}}
function twwx()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#EEEEEE';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji6.js"
var request=new XMLHttpRequest();request.open("get",url);request.send(null);request.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var yuezhi1=bazi.getMonth().substr(-1);var rigan1=bazi.getDay().substr(0,1);var heji='';heji+=bazi.getMonth().substr(-1)+','+bazi.getDay().substr(0,1)+','+bazi.getTime();var ttt='';$('#span666').html('月支/日干/时柱：'+heji);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ttt+=json.data[i].content+'<br>';$('#text666').html('<b style="color:#000000;">月支/日干/时柱：'+heji+'：</b><br>'+ttt);}}}}}
function wxjj()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#EEEEEE';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji7_1.js"
var url2="guji7_2.js"
var url3="guji7_3.js"
var url4="guji7_4.js"
var url5="guji7_5.js"
var request=new XMLHttpRequest();var request2=new XMLHttpRequest();var request3=new XMLHttpRequest();var request4=new XMLHttpRequest();var request5=new XMLHttpRequest();request.open("get",url);request2.open("get",url2);request3.open("get",url3);request4.open("get",url4);request5.open("get",url5);request.send(null);request2.send(null);request3.send(null);request4.send(null);request5.send(null);request.onload=request2.onload=request3.onload=request4.onload=request5.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var heji='';heji+=bazi.getDay();var heji22='';heji22+=bazi.getYear();var ttt='';var ttt11='';$('#span666').html('日柱/年柱：'+heji+'/'+heji22);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ ttt+=json.data[i].content+'<br>';}
if(json.data[i].key==heji22){ttt11+=json.data[i].content+'<br>';}}}
if(request2.status==200){var json=JSON.parse(request2.responseText);var heji2='';heji2+=bazi.getDay().substr(0,1);var ttt2='';$('#span777').html('日干：'+heji2);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji2){ttt2+=json.data[i].content+'<br>';}}}
if(request3.status==200){var json=JSON.parse(request3.responseText);var rigan1=bazi.getDay().substr(0,1);var wuxing='';if(rigan1=='甲'||rigan1=='乙'){wuxing='木';}
if(rigan1=='丙'||rigan1=='丁'){wuxing='火';}
if(rigan1=='戊'||rigan1=='己'){wuxing='土';}
if(rigan1=='庚'||rigan1=='辛'){wuxing='金';}
if(rigan1=='壬'||rigan1=='癸'){wuxing='水';}
var heji3='';heji3+=wuxing;var ttt3='';$('#span888').html('日干五行：'+heji3);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji3){ttt3+=json.data[i].content+'<br>';}}}
if(request4.status==200){var json=JSON.parse(request4.responseText);var heji4='';heji4+=bazi.getDay()+','+bazi.getTime();var ttt4='';$('#span999').html('日柱/时柱：'+heji4);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji4){ttt4+=json.data[i].content;}}}
if(request5.status==200){var json=JSON.parse(request5.responseText);var heji5='';heji5+=bazi.getMonth().substr(-1);var ttt5='';$('#span000').html('月支：'+heji5);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji5){ttt5+=json.data[i].content+'<br>';}}}
$('#text666').html('<b style="color:#000000;">日柱/年柱：'+heji+'/'+heji22+'：</b><br>'+ttt+ttt11+'<b style="color:#000000;">日干：'+heji2+'：</b><br>'+ttt2+'<b style="color:#000000;">日干五行：'+heji3+'：</b><br>'+ttt3+'<b style="color:#000000;">日柱/时柱：'+heji4+'：</b><br>'+ttt4+'<b style="color:#000000;">月支：'+heji5+'：</b><br>'+ttt5);}}
function xzms()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#EEEEEE';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var url="guji8_1.js"
var request=new XMLHttpRequest();request.open("get",url);request.send(null);request.onload=function(){if(request.status==200){var json=JSON.parse(request.responseText);var heji='';heji+=bazi.getDay();var heji2='';heji2+=bazi.getYear();var ttt='';var ttt1='';$('#span666').html('日柱/年柱：'+heji+'/'+heji2);for(var i=0;i<json.data.length;i++){if(json.data[i].key==heji){ttt+=json.data[i].content+'<br>';}
if(json.data[i].key==heji2){ ttt1+=json.data[i].content+'<br>';}
$('#text666').html('<b style="color:#000000;">日柱/年柱：'+heji+'/'+heji2+'：</b><br>'+ttt+ttt1);}}}}
function qtbj()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#EEEEEE';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);
var rigan12=bazi.getDay().substr(0,1);
var wuxing='';
if(rigan12=='甲'||rigan12=='乙'){wuxing='木';}
if(rigan12=='丙'||rigan12=='丁'){wuxing='火';}
if(rigan12=='戊'||rigan12=='己'){wuxing='土';}
if(rigan12=='庚'||rigan12=='辛'){wuxing='金';}
if(rigan12=='壬'||rigan12=='癸'){wuxing='水';}
var heji='';heji=rigan12+wuxing+month;
var ttt='';$('#span666').html('日干/日干五行/月份：'+heji);ttt+=qtbj1(heji);$('#text666').html('<b style="color:#000000;">日干/日干五行/月份：'+heji+'月</b><br>'+ttt);}
function fdzj1()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#EEEEEE';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var heji='';heji=bazi.getYear().substr(0,1)+bazi.getTime().substr(0,1);var ttt='';ttt+=fdzj(heji)+'<br><b style="color:#000000;">详解如下<br>时辰为星：'+bazi.getTime()+'</b><br>'+ltq(heji);$('#text666').html('<b style="color:#000000;">年干时干：'+heji+'</b><br>'+ttt);}
function lyb()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#EEEEEE';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);            

var heji='';
heji=bazi.getDay().substr(-1);
var ttt='';
ttt+=lingyiban(heji);
var niannian=bazi.getYear();
var yueyue=bazi.getMonth();
var riri=bazi.getDay();
var shishi=bazi.getTime();
var txtnn='';var nannv='';
/*
if(gender==1){nannv='男';}
if(gender==0){nannv='女';}
txtnn+='<b style="color:#000000;">你自己选择的性别是：</b>'+nannv+'<br><b style="color:#000000;">你头胎小孩的性别是：</b>';if(gender=='1')
{var rigan=riri.substr(0,1);var shizhi=shishi.substr(-1);if((rigan=='乙'||rigan=='丁'||rigan=='己'||rigan=='辛'||rigan=='癸')&&(shizhi=='子'||shizhi=='寅'||shizhi=='辰'||shizhi=='午'||shizhi=='申'||shizhi=='戌'))
{txtnn+='男';}
if((rigan=='乙'||rigan=='丁'||rigan=='己'||rigan=='辛'||rigan=='癸')&&(shizhi=='丑'||shizhi=='卯'||shizhi=='巳'||shizhi=='未'||shizhi=='酉'||shizhi=='亥')){txtnn+='女';}
if((shizhi=='丑'||shizhi=='卯'||shizhi=='巳'||shizhi=='未'||shizhi=='酉'||shizhi=='亥')&&(rigan=='甲'||rigan=='丙'||rigan=='戊'||rigan=='庚'||rigan=='壬'))
{txtnn+='女';}
if((shizhi=='子'||shizhi=='寅'||shizhi=='辰'||shizhi=='午'||shizhi=='申'||shizhi=='戌')&&(rigan=='甲'||rigan=='丙'||rigan=='戊'||rigan=='庚'||rigan=='壬'))
{txtnn+='男';}}
if(gender=='0')
{var rigan=riri.substr(0,1);var shizhi=shishi.substr(-1);if((rigan=='乙'||rigan=='丁'||rigan=='己'||rigan=='辛'||rigan=='癸')&&(shizhi=='丑'||shizhi=='卯'||shizhi=='巳'||shizhi=='未'||shizhi=='酉'||shizhi=='亥')){txtnn+='男';}
if((rigan=='乙'||rigan=='丁'||rigan=='己'||rigan=='辛'||rigan=='癸')&&(shizhi=='子'||shizhi=='寅'||shizhi=='辰'||shizhi=='午'||shizhi=='申'||shizhi=='戌'))
{txtnn+='女';}
if((shizhi=='子'||shizhi=='寅'||shizhi=='辰'||shizhi=='午'||shizhi=='申'||shizhi=='戌')&&(rigan=='甲'||rigan=='丙'||rigan=='戊'||rigan=='庚'||rigan=='壬'))
{txtnn+='女';}
if((shizhi=='丑'||shizhi=='卯'||shizhi=='巳'||shizhi=='未'||shizhi=='酉'||shizhi=='亥')&&(rigan=='甲'||rigan=='丙'||rigan=='戊'||rigan=='庚'||rigan=='壬'))
{txtnn+='男';}}
*/

//三命通会内容↓
var niannian=lunar.getYearInGanZhiExact();
var yueyue=lunar.getMonthInGanZhiExact();
var riri=bazi.getDay();
var shishi=bazi.getTime();
var ssrr=riri+shishi;
var shiri_h=rishi(ssrr);
txtnn +=''+shiri_h+'<p>';


var rixx=rixiangxi(riri);
txtnn+=''+rixx+'';

/*
var yuezhi=yueyue.substr(-1);
var nianzhi=niannian.substr(-1);
var qsjs=sanshishu(yuezhi+nianzhi);
txtnn+='<br><!--br>【前世今生详情】<br>'+qsjs;

var niangan=niannian.substr(0,1);
var fulubiao=lu(niangan+yuezhi);
txtnn+='<br--><br>【福禄详情】<br>'+fulubiao;
var nvdishi=bazi.getDayDiShi();
var fq=fuqi(nvdishi);
txtnn+='<br><br>【女性夫妻缘分】<br>'+fq;
*/
$('#text666').html('<!--b style="color:#000000;">你的另一半</b><br>'+ttt+'<br-->'+txtnn+'');  } 

function gwzy()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#EEEEEE';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var heji='';heji=bazi.getDay();var ttt='';ttt+=gewuzhiyan(heji);$('#text666').html('<b style="color:#000000;">日柱：'+heji+'</b><br>'+ttt);}
function wglm1()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#EEEEEE';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var rigan=bazi.getDay().substr(0,1);var jijie='';if(lunar.getMonthInChinese()=='正'||lunar.getMonthInChinese()=='二'||lunar.getMonthInChinese()=='三'||lunar.getMonthInChinese()=='闰二')
{jijie='春';}
if(lunar.getMonthInChinese()=='四'||lunar.getMonthInChinese()=='五'||lunar.getMonthInChinese()=='六')
{jijie='夏';}
if(lunar.getMonthInChinese()=='七'||lunar.getMonthInChinese()=='八'||lunar.getMonthInChinese()=='九')
{jijie='秋';}
if(lunar.getMonthInChinese()=='十'||lunar.getMonthInChinese()=='冬'||lunar.getMonthInChinese()=='腊')
{jijie='冬';}
var heji='';heji=rigan+jijie;var ttt='';ttt+=wglm(heji);$('#text666').html('<b style="color:#000000;">日干季节：'+heji+'</b><br><br>'+ttt);}
function bzmg()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#EEEEEE';document.getElementById('cgsm').style.backgroundColor='#ffffff';var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);var nianzhi=bazi.getYear().substr(-1);var yueyue=lunar.getMonthInChinese();var riri=lunar.getDayInChinese();var abcdef=Number(niangong(nianzhi))+Number(yuegong(yueyue))+Number(rigong(riri))+Number(shigong(hour));var bbccdd='';var heji='';heji+=abcdef/10;bbccdd+=minggong(abcdef);$('#text666').html('<b style="color:#000000;">'+heji+'宫度：</b>'+bbccdd);}
function cgsm()
{document.getElementById('dtss').style.backgroundColor='#ffffff';document.getElementById('xsys').style.backgroundColor='#ffffff';document.getElementById('smth').style.backgroundColor='#ffffff';document.getElementById('sftk').style.backgroundColor='#ffffff';document.getElementById('bzty').style.backgroundColor='#ffffff';document.getElementById('twwx').style.backgroundColor='#ffffff';document.getElementById('wxjj').style.backgroundColor='#ffffff';document.getElementById('qtbj').style.backgroundColor='#ffffff';document.getElementById('xzms').style.backgroundColor='#ffffff';document.getElementById('fdzj').style.backgroundColor='#ffffff';document.getElementById('lyb').style.backgroundColor='#ffffff';document.getElementById('gwzy').style.backgroundColor='#ffffff';document.getElementById('wglm').style.backgroundColor='#ffffff';document.getElementById('bzmg').style.backgroundColor='#ffffff';document.getElementById('cgsm').style.backgroundColor='#EEEEEE';
var year=$('#year').val();var month=$('#month').val();var day=$('#day').val();var hour=$('#hour').val();var minute=$('#minute').val();var gender=parseInt($('#gender').val());var sect=parseInt($('#sect').val());var solar=Solar.fromYmdHms(year,month,day,hour,minute,0);var lunar=solar.getLunar();var bazi=lunar.getEightChar();bazi.setSect(sect);
var niannian=bazi.getYear();
var yueyue=lunar.getMonthInChinese();
var riri=lunar.getDayInChinese();
var abcdef=Number(nianzhong(niannian))+Number(yuezhong(yueyue))+Number(rizhong(riri))+Number(shizhong(hour));
var bbccdd='';bbccdd+=chengguzhong(abcdef);$('#text666').html(bbccdd);}